### ISSUE TITLE
data

### ISSUE THREAD

**Issue by pythonxcj** [irugina/meta-image-translation#3]
Hello, I am honored to be able to learn this project, which has greatly benefited me. I have a question.
dataroot=/home/gridsan/groups/EarthIntelligence/datasets/SEVIR/**image_translation/**，      
 Is this data  sevir file generated by running prepare_sevir_dataset.py?  
Thank you very much for answering my question. I'm sorry to disturb you.

**Comment by irugina** [comment]
Thank you for your interest in our work and apologies for leaving local paths in this repo. Yes, that's correct, they are generated with `prepare_sevir_dataset.py`. Access to the original dataset is described [here](https://github.com/MIT-AI-Accelerator/sevir_challenges/blob/main/radar_nowcasting/RadarNowcastBenchmarks.ipynb).

**Comment by pythonxcj** [comment]
Thank you for taking time out of your busy schedule to answer my questions, which makes me feel very honored. I wish you every success in your work.

**Comment by pythonxcj** [comment]
When I try to run train_unet.py ,I get an error.I don't know if you have encountered this problem？Thank you for going through my question.

Traceback (most recent call last):
  File "train_unet.py", line 67, in <module>
    train_fn(model, train_dataloader, opt, epoch)
  File "E:\meta-image-translation\utils\train.py", line 81, in train_joint_reconstruction
    for count, train_batch in enumerate(train_dataloader):
  File "D:\ProgramData\Anaconda3\envs\rectflow\lib\site-packages\torch\utils\data\dataloader.py", line 530, in __next__
    data = self._next_data()
  File "D:\ProgramData\Anaconda3\envs\rectflow\lib\site-packages\torch\utils\data\dataloader.py", line 570, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\ProgramData\Anaconda3\envs\rectflow\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\ProgramData\Anaconda3\envs\rectflow\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\meta-image-translation\data\sevir_dataset.py", line 123, in __getitem__
    AB= read_npy_chunk(AB_path, 0, n_samples_per_task)
  File "E:\meta-image-translation\data\sevir_dataset.py", line 56, in read_npy_chunk
    flat = np.fromfile(fhandle, count=n_items, dtype=dtype)
**ValueError: Cannot read into object array**

**Comment by pythonxcj** [comment]
> 感谢您对我们工作的关注，并为此存储库中留下本地路径而道歉。是的，没错，它们是用.[此处](https://github.com/MIT-AI-Accelerator/sevir_challenges/blob/main/radar_nowcasting/RadarNowcastBenchmarks.ipynb)介绍了对原始数据集的访问。`prepare_sevir_dataset.py`
